#!/usr/bin/env python3
"""
Build a draft security report from a completed worksheet.

Input worksheet format:
- CSV generated by build_security_review_sheet.py
- JSON generated by build_security_review_sheet.py
"""

from __future__ import annotations

import argparse
import csv
import json
from collections import Counter
from datetime import date
from pathlib import Path
from typing import Any

SEVERITY_ORDER = {
    "critical": 0,
    "high": 1,
    "medium": 2,
    "low": 3,
    "info": 4,
    "": 5,
}

POSITIVE_FINDING_STATUSES = {"confirmed", "likely"}
NO_FINDING_STATUSES = {"no_issue", "not_found", "clean"}
FOLLOW_UP_STATUSES = {"follow_up", "needs_follow_up", "pending", "blocked"}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Build a draft security review report")
    parser.add_argument("--worksheet", required=True, help="Worksheet CSV or JSON path")
    parser.add_argument("--output", help="Optional output file path")
    parser.add_argument("--target", default="", help="Target system or URL")
    parser.add_argument("--environment", default="", help="Environment name")
    parser.add_argument("--swagger-source", default="", help="Swagger or OpenAPI source")
    parser.add_argument(
        "--auth-context",
        action="append",
        default=[],
        help="Authentication context used during testing; repeatable",
    )
    parser.add_argument(
        "--input-note",
        action="append",
        default=[],
        help="Input provided for the assessment; repeatable",
    )
    parser.add_argument(
        "--codebase-area",
        action="append",
        default=[],
        help="Codebase area or module reviewed; repeatable",
    )
    parser.add_argument(
        "--constraint",
        action="append",
        default=[],
        help="Testing constraint or limitation; repeatable",
    )
    parser.add_argument(
        "--site-check",
        action="append",
        default=[],
        help="Site-level or platform-level check performed; repeatable",
    )
    parser.add_argument(
        "--metadata-json",
        help="Optional JSON file with report metadata fields",
    )
    return parser.parse_args()


def normalize_row(entry: dict[str, Any]) -> dict[str, str]:
    return {str(key): "" if value is None else str(value) for key, value in entry.items()}


def load_worksheet(path: str) -> list[dict[str, str]]:
    source = Path(path)
    suffix = source.suffix.lower()

    if suffix == ".json":
        data = json.loads(source.read_text(encoding="utf-8"))
        if not isinstance(data, list):
            raise ValueError("Worksheet JSON must be a list")
        return [normalize_row(entry) for entry in data if isinstance(entry, dict)]

    with source.open(encoding="utf-8", newline="") as handle:
        reader = csv.DictReader(handle)
        return [normalize_row(row) for row in reader]


def merge_metadata(args: argparse.Namespace) -> dict[str, Any]:
    metadata: dict[str, Any] = {
        "target": args.target,
        "environment": args.environment,
        "swagger_source": args.swagger_source,
        "auth_contexts": args.auth_context,
        "input_notes": args.input_note,
        "codebase_areas": args.codebase_area,
        "constraints": args.constraint,
        "site_checks": args.site_check,
    }

    if args.metadata_json:
        extra = json.loads(Path(args.metadata_json).read_text(encoding="utf-8"))
        if not isinstance(extra, dict):
            raise ValueError("metadata-json must contain a JSON object")
        for key, value in extra.items():
            metadata[key] = value

    return metadata


def sort_findings(rows: list[dict[str, str]]) -> list[dict[str, str]]:
    return sorted(
        rows,
        key=lambda row: (
            SEVERITY_ORDER.get(row.get("severity", "").strip().lower(), 99),
            row.get("path", ""),
            row.get("method", ""),
        ),
    )


def summarize_coverage(rows: list[dict[str, str]]) -> dict[str, int]:
    runtime_tested = sum(1 for row in rows if row.get("runtime_tested", "").lower() == "yes")
    findings = sum(
        1 for row in rows if row.get("finding_status", "").strip().lower() in POSITIVE_FINDING_STATUSES
    )
    clean = sum(
        1 for row in rows if row.get("finding_status", "").strip().lower() in NO_FINDING_STATUSES
    )
    follow_up = len(rows) - findings - clean
    return {
        "total": len(rows),
        "runtime_tested": runtime_tested,
        "findings": findings,
        "clean": clean,
        "follow_up": follow_up,
    }


def highest_risk_summary(findings: list[dict[str, str]]) -> list[str]:
    bullets = []
    for row in findings[:5]:
        title = row.get("finding_title") or row.get("vulnerability_type") or "Unnamed finding"
        bullets.append(
            f"{row.get('severity', 'unspecified').upper()}: {title} on {row.get('method', '')} {row.get('path', '')}"
        )
    return bullets


def list_or_placeholder(values: Any, placeholder: str = "Not provided") -> list[str]:
    if isinstance(values, list):
        cleaned = [str(value).strip() for value in values if str(value).strip()]
        return cleaned or [placeholder]
    if isinstance(values, str) and values.strip():
        return [values.strip()]
    return [placeholder]


def row_summary_status(row: dict[str, str]) -> str:
    status = row.get("finding_status", "").strip().lower()
    if status in POSITIVE_FINDING_STATUSES:
        title = row.get("finding_title") or row.get("vulnerability_type") or "issue found"
        return f"issue found: {title}"
    if status in NO_FINDING_STATUSES:
        return "no issue found"
    return "needs follow-up"


def render_report(rows: list[dict[str, str]], metadata: dict[str, Any]) -> str:
    findings = sort_findings(
        [
            row
            for row in rows
            if row.get("finding_status", "").strip().lower() in POSITIVE_FINDING_STATUSES
        ]
    )
    clean_rows = [
        row for row in rows if row.get("finding_status", "").strip().lower() in NO_FINDING_STATUSES
    ]
    follow_up_rows = [
        row for row in rows if row.get("finding_status", "").strip().lower() in FOLLOW_UP_STATUSES
    ]
    coverage = summarize_coverage(rows)
    severities = Counter(row.get("severity", "").strip().lower() or "unspecified" for row in findings)

    lines: list[str] = []
    lines.append("# Security Review Report")
    lines.append("")
    lines.append("## 1. Executive Summary")
    lines.append("")
    lines.append(f"- Target: {metadata.get('target') or 'Not provided'}")
    lines.append(f"- Environment: {metadata.get('environment') or 'Not provided'}")
    lines.append(f"- Review date: {date.today().isoformat()}")
    lines.append(f"- Inputs provided: {', '.join(list_or_placeholder(metadata.get('input_notes')))}")
    lines.append(
        "- Coverage summary: "
        f"{coverage['total']} endpoints reviewed, {coverage['runtime_tested']} runtime-tested, "
        f"{coverage['findings']} with findings, {coverage['clean']} with no confirmed issue, "
        f"{coverage['follow_up']} requiring follow-up"
    )
    if severities:
        severity_text = ", ".join(
            f"{count} {severity}" for severity, count in sorted(severities.items(), key=lambda item: SEVERITY_ORDER.get(item[0], 99))
        )
        lines.append(f"- Highest-risk findings: {severity_text}")
    else:
        lines.append("- Highest-risk findings: No confirmed findings recorded yet")
    for bullet in highest_risk_summary(findings):
        lines.append(f"- {bullet}")

    lines.append("")
    lines.append("## 2. Scope And Constraints")
    lines.append("")
    lines.append(f"- In-scope systems: {metadata.get('target') or 'Not provided'}")
    lines.append(f"- Auth contexts used: {', '.join(list_or_placeholder(metadata.get('auth_contexts')))}")
    lines.append(f"- Swagger or OpenAPI source: {metadata.get('swagger_source') or 'Not provided'}")
    lines.append(f"- Codebase areas reviewed: {', '.join(list_or_placeholder(metadata.get('codebase_areas')))}")
    lines.append(f"- Testing constraints: {', '.join(list_or_placeholder(metadata.get('constraints')))}")
    lines.append("- `/internal` handling note: `/internal` endpoints were assessed primarily through code review and trust-boundary analysis.")

    lines.append("")
    lines.append("## 3. Methodology")
    lines.append("")
    lines.append("- Endpoint inventory generated from Swagger or OpenAPI and expanded into a per-endpoint worksheet.")
    lines.append("- Code mapping from routes to handlers, services, and data access paths.")
    lines.append("- Static review categories applied: access control, XSS, injection, CSRF, sensitive data exposure, and auth/session controls.")
    lines.append("- Live verification focused on low-impact requests and header or behavior inspection.")
    site_checks = list_or_placeholder(metadata.get("site_checks"), "Standard site-level checks performed as permitted")
    lines.append(f"- Site-level configuration checks performed: {', '.join(site_checks)}")

    lines.append("")
    lines.append("## 4. Coverage Matrix")
    lines.append("")
    lines.append("| Method | Path | Auth | Code Paths | Live Tested | Result |")
    lines.append("| --- | --- | --- | --- | --- | --- |")
    for row in rows:
        lines.append(
            "| "
            + " | ".join(
                [
                    row.get("method", "").replace("|", "\\|"),
                    row.get("path", "").replace("|", "\\|"),
                    row.get("auth", "").replace("|", "\\|"),
                    row.get("code_paths", "").replace("|", "\\|"),
                    row.get("runtime_tested", "").replace("|", "\\|"),
                    row_summary_status(row).replace("|", "\\|"),
                ]
            )
            + " |"
        )

    lines.append("")
    lines.append("## 5. Findings")
    lines.append("")
    if not findings:
        lines.append("No confirmed or likely findings were recorded in the worksheet.")
    else:
        for row in findings:
            title = row.get("finding_title") or row.get("vulnerability_type") or "Unnamed finding"
            vuln_type = row.get("vulnerability_type") or "Not specified"
            lines.append(f"### [{row.get('severity', 'UNSPECIFIED').upper()}] {title}")
            lines.append("")
            lines.append(f"- Vulnerability type: {vuln_type}")
            lines.append(f"- Affected endpoint(s): {row.get('method', '')} {row.get('path', '')}")
            lines.append(f"- Auth context required: {row.get('auth') or 'Not specified'}")
            lines.append(f"- Code location: {row.get('code_paths') or 'Not recorded'}")
            lines.append(f"- Evidence: {row.get('evidence') or row.get('notes') or 'Not recorded'}")
            lines.append(f"- Exploit summary: {row.get('notes') or 'Not recorded'}")
            lines.append(f"- Impact: {row.get('impact') or 'Not recorded'}")
            lines.append(f"- Confidence: {row.get('confidence') or 'Not specified'}")
            lines.append(f"- Remediation: {row.get('remediation') or 'Not recorded'}")
            lines.append("")

    lines.append("## 6. Endpoints Reviewed Without Findings")
    lines.append("")
    if not clean_rows:
        lines.append("No endpoints are currently marked as reviewed-without-findings.")
    else:
        for row in clean_rows:
            lines.append(
                f"- {row.get('method', '')} {row.get('path', '')}"
                + (f" ({row.get('code_paths')})" if row.get("code_paths") else "")
            )

    lines.append("")
    lines.append("## 7. Open Questions And Follow-Up")
    lines.append("")
    if not follow_up_rows:
        lines.append("- No open follow-up items recorded.")
    else:
        for row in follow_up_rows:
            lines.append(
                f"- {row.get('method', '')} {row.get('path', '')}: "
                f"{row.get('notes') or row.get('risk_focus') or 'Needs further review'}"
            )

    return "\n".join(lines) + "\n"


def main() -> int:
    args = parse_args()
    rows = load_worksheet(args.worksheet)
    metadata = merge_metadata(args)
    report = render_report(rows, metadata)

    if args.output:
        Path(args.output).write_text(report, encoding="utf-8")
    else:
        print(report, end="")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
